# IMPORT LIBRARIES

In [1]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

# TIMING CHECKING

In [9]:
l1=[1,2,3]
l2=[3,4,5]
#we will create a list like [1*3,2*4,3*5]
%timeit list(map(lambda x,y : x*y,l1,l2))

783 ns ± 25.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
npA1=np.array([1,2,3])
npA2=np.array([3,4,5])
#we will create a list like [1*3,2*4,3*5]
%timeit npA1*npA2

624 ns ± 21.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# NUMPY FUNDEMENTALS

In [27]:
puku=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [28]:
puku

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
puku.shape

(3, 4)

In [30]:
puku.dtype

dtype('int32')

In [31]:
puku.ndim#According to list of list concept

2

In [32]:
puli=np.arange(1,10)

In [33]:
puli

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
puli.dtype

dtype('int32')

In [35]:
pylist=range(0,10)

In [36]:
pylist

range(0, 10)

In [37]:
puli

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
chopechul=np.array([[1,0,0],[0,1,0],[0,0,1]])
chopechul

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [42]:
chopechul=np.eye(5)

In [43]:
chopechul

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
chopechul.dtype

dtype('float64')

In [46]:
chopechul.itemsize

8

In [49]:
gurde=np.full((10,10),9)

In [50]:
gurde

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [51]:
gurde.shape

(10, 10)

In [52]:
#[v,v
# v,v
# v,v]
#(3,2)
v=[1,3,4]
np.tile(v,(3,2))

array([[1, 3, 4, 1, 3, 4],
       [1, 3, 4, 1, 3, 4],
       [1, 3, 4, 1, 3, 4]])

In [53]:
puku

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
puku.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [59]:
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

# SLICING PART IN NUMPY

In [60]:
puku

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
puku[1,2]

7

In [62]:
puku.shape

(3, 4)

In [65]:
puku2=puku.reshape(6,2)

In [66]:
puku2.shape

(6, 2)

In [67]:
puku2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [68]:
puku[1]

array([5, 6, 7, 8])

In [69]:
puku

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
puli.shape

(9,)

In [77]:
puli[:,np.newaxis].shape

(9, 1)

In [78]:
puku[2]

array([ 9, 10, 11, 12])

In [82]:
puku[puku>6]

array([ 7,  8,  9, 10, 11, 12])

In [83]:
puku

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
chaat=np.array([[1,0,4,0],[0,1,0,9],[0,0,1,6]])

In [87]:
chaat

array([[1, 0, 4, 0],
       [0, 1, 0, 9],
       [0, 0, 1, 6]])

In [88]:
np.vstack((puku,chaat))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  0,  4,  0],
       [ 0,  1,  0,  9],
       [ 0,  0,  1,  6]])

In [89]:
np.hstack((puku,chaat))

array([[ 1,  2,  3,  4,  1,  0,  4,  0],
       [ 5,  6,  7,  8,  0,  1,  0,  9],
       [ 9, 10, 11, 12,  0,  0,  1,  6]])

# MATHEMATICAL PART AND 
# LINEAR ALGEBRA

In [90]:
puku

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
np.sin(puku)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825],
       [ 0.41211849, -0.54402111, -0.99999021, -0.53657292]])

In [92]:
np.cos(puku)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003],
       [-0.91113026, -0.83907153,  0.0044257 ,  0.84385396]])

In [93]:
np.median(puku)

6.5

In [94]:
np.exp(puku)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [95]:
puku

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [99]:
sm=np.array([[1,2,9],[4,5,6],[7,8,9]])
sm

array([[1, 2, 9],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
np.linalg.det(sm)

-18.000000000000014

In [101]:
np.linalg.inv(sm)

array([[ 0.16666667, -3.        ,  1.83333333],
       [-0.33333333,  3.        , -1.66666667],
       [ 0.16666667, -0.33333333,  0.16666667]])

In [102]:
np.linalg.eig(sm)

(array([18.23605815, -3.51673219,  0.28067404]),
 array([[-0.44951268, -0.89764884,  0.6894365 ],
        [-0.47793818,  0.12356766, -0.71681381],
        [-0.75466115,  0.42303379,  0.10418867]]))

In [103]:
sm

array([[1, 2, 9],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
sm2=np.array([[1,2,9],[4,5,6],[7,8,9]])

In [2]:
laora=np.dot(sm,sm2)

NameError: name 'np' is not defined

In [109]:
laora.argmax()#REturn Index OF Maximum Value of A matrix

8

In [118]:
puli2=np.array([1,5,9,7,820,58,96,5,2,4])
puli2

array([  1,   5,   9,   7, 820,  58,  96,   5,   2,   4])

In [122]:
np.sort(puli2)#Sorting Numpy Array

array([  1,   2,   4,   5,   5,   7,   9,  58,  96, 820])

In [110]:
laora

array([[ 72,  84, 102],
       [ 66,  81, 120],
       [102, 126, 192]])

In [111]:
laora.sum(axis=0)

array([240, 291, 414])

In [115]:
laora.sum(axis=1)

array([258, 267, 420])

In [114]:
#MATRIX MULTIPLICATION
import numpy as np
r1=int(input("Enter the no of rows of 1st matrix :: "))
c1=int(input("Enter the no of columns of 1st matrix :: "))
r2=int(input("Enter the no of rows of 2nd matrix :: "))
c2=int(input("Enter the no of columns of 2nd matrix :: "))
print("Enter the {} entries in a Matrix 1 (separated by space): ".format(r1*c1)) 
entries1 = list(map(int, input().split())) 
matrix1=np.array(entries1).reshape(r1,c1)
print("Enter the {} entries in a Matrix 2 (separated by space): ".format(r2*c2)) 
entries2 = list(map(int, input().split())) 
matrix2=np.array(entries2).reshape(r2,c2)
print("MATRIX-1: \n",matrix1)
print("MATRIX-2: \n",matrix2)
mulmat=np.dot(matrix1,matrix2)
print(mulmat)

Enter the no of rows of 1st matrix :: 2
Enter the no of columns of 1st matrix :: 2
Enter the no of rows of 2nd matrix :: 2
Enter the no of columns of 2nd matrix :: 2
Enter the 4 entries in a Matrix 1 (separated by space): 
5 5 5 5
Enter the 4 entries in a Matrix 2 (separated by space): 
5 5 5 5
MATRIX-1: 
 [[5 5]
 [5 5]]
MATRIX-2: 
 [[5 5]
 [5 5]]
[[50 50]
 [50 50]]


# HAPPY CODING -- NUMPY FINISHED